name: assistant_pro
description: Your daily virtual assistant
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: ./domain
  presentation:
    path: ./presentation
  data:
    path: ./data
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.0
  get_it: ^7.6.7
  go_router: ^13.0.0
  injectable: ^2.3.5
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  injectable_generator: ^2.4.2
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
