name: presentation
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  domain:
    path: ../domain
  get_it: ^7.6.7
  injectable: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
