name: domain
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  async: ^2.11.0
  google_generative_ai: ^0.3.1
  injectable: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
